import React,{useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import'./style.css'

const A='./assets/'
const MAP='https://www.google.com/search?kgmid=%2Fg%2F11tx5kzs7l&hl=en-PK&q=%D8%A7%D9%84%D9%85%D8%B7%D9%8A%D8%B1%D9%8A%20%D9%84%D9%84%D9%81%D9%8A%D8%A8%D8%B1%20%D8%AC%D8%AF%D9%87&shem=epsd1%2Cltae%2Crimspwouoe&shndl=30&source=sh%2Fx%2Floc%2Fosrp%2Fm1%2F4&kgs=ec741a6e5962296b'
const PHONE='+966 50 251 1885',WA='https://wa.me/966502511885'

const I18N={
 en:{
  nav:{home:'Home',about:'About',products:'Products',showcase:'Showcase',documents:'Documents',faq:'FAQ',contact:'Contact'},
  buttons:{explore:'Explore Products →',whatsapp:'WhatsApp Us',discover:'Discover our story →',view:'View More ↗',message:'Message on WhatsApp →',maps:'Open Google Maps ↗',conversation:'Start a conversation →',send:'Send via WhatsApp →',openLocation:'Open exact Google Maps location ↗'},
  home:{eyebrow:'AL-MUTAIRI FIBER GLASS • JEDDAH, SAUDI ARABIA',title:'Fiberglass solutions,',title2:'crafted to last.',desc:'Professional fiberglass products, custom fabrication and dependable service for homes, businesses and industry.',stats:['Products','Categories','Saudi Arabia'],company:'OUR COMPANY',companyTitle:'Built for strength.',companyTitle2:'Designed for purpose.',companyDesc:'Al-Mutairi Fiber Glass provides practical, durable and custom fiberglass solutions with a focus on quality workmanship and customer requirements.',categories:'Explore Categories',featured:'Featured Products',showcase:'Visual Showcase',documents:'Company Documents',contactEyebrow:'GET IN TOUCH',contactTitle:'Let’s build something',contactTitle2:'strong together.',contactDesc:'Tell us about your project and contact our team directly.'},
 pages:{about:{title:'About Al-Mutairi',sub:'A practical fiberglass partner in Jeddah.',eyebrow:'OUR APPROACH',heading:'Quality is not a feature.',heading2:'It is the standard.',p1:'Al-Mutairi Fiber Glass is focused on durable fiberglass work, custom fabrication and solutions built around real customer needs.',p2:'From everyday products to specialized requirements, our goal is straightforward: reliable workmanship, useful design and service you can trust.'},products:{title:'Our Products',sub:'50 products across eight practical fiberglass categories.'},showcase:{title:'Visual Showcase',sub:'Explore our work through our showcase videos.'},documents:{title:'Company Documents',sub:'Browse all available company documents.'},faq:{title:'Frequently Asked Questions',sub:'Quick answers about products, service and contact.'},contact:{title:'Get in Touch',sub:'Tell us what you need and contact us directly.'}},
 categories:['Tanks & Containers','Canopies & Shades','Doors & Windows','Industrial Fiberglass','Marine & Outdoor','Custom Fabrication','Decorative Fiberglass','Repair & Maintenance'],
 categoryDesc:['Durable tanks and storage solutions.','Weather-resistant shade and canopy solutions.','Strong, low-maintenance doors and windows.','Practical solutions for industrial environments.','Fiberglass products for marine and outdoor use.','Made-to-measure fiberglass fabrication.','Decorative pieces with durable finishes.','Repair, restoration and maintenance services.'],
 productModel:'Model',productSearch:'Search products…',all:'All',view:'VIEW',documents:'Company Document',faqNum:'',
 faqs:[['What products does Al-Mutairi Fiber Glass provide?','We provide fiberglass products and custom solutions for residential, commercial, industrial, marine and outdoor requirements.'],['Where is Al-Mutairi Fiber Glass located?','Al-Mutairi Fiber Glass is located on 30th Street, near 60th, Jeddah 23448, Saudi Arabia.'],['Can you make custom fiberglass products?','Yes. Share your dimensions, quantity, reference images and requirements through WhatsApp for a custom quotation.'],['How can I request a quotation?','Use the Get in Touch form or WhatsApp button and tell us what you need.'],['Do you offer repair and maintenance?','Yes, repair and maintenance can be discussed according to the product and project condition.'],['How can I contact the company?','Call +966 50 251 1885 or contact us on WhatsApp.']],
 footer:{desc:'Professional fiberglass solutions in Jeddah, Saudi Arabia.',explore:'Explore',contact:'Contact',maps:'Google Maps'},form:{name:'Name',phone:'Phone',message:'Message'}
 },
 ar:{
  nav:{home:'الرئيسية',about:'من نحن',products:'المنتجات',showcase:'المعرض',documents:'الوثائق',faq:'الأسئلة الشائعة',contact:'تواصل معنا'},
  buttons:{explore:'استكشف المنتجات ←',whatsapp:'تواصل عبر واتساب',discover:'اكتشف قصتنا ←',view:'عرض المزيد ↗',message:'راسلنا عبر واتساب ←',maps:'فتح خرائط جوجل ↗',conversation:'ابدأ محادثة ←',send:'إرسال عبر واتساب ←',openLocation:'فتح موقعنا على خرائط جوجل ↗'},
  home:{eyebrow:'المطيري للفيبر جلاس • جدة، المملكة العربية السعودية',title:'حلول الفيبر جلاس،',title2:'مصممة لتدوم.',desc:'منتجات فيبر جلاس احترافية، تصنيع حسب الطلب وخدمة موثوقة للمنازل والشركات والقطاع الصناعي.',stats:['المنتجات','الفئات','المملكة العربية السعودية'],company:'شركتنا',companyTitle:'قوة تدوم.',companyTitle2:'وتصميم عملي.',companyDesc:'يوفر المطيري للفيبر جلاس حلولاً عملية ومتينة ومخصصة من الفيبر جلاس مع التركيز على جودة التنفيذ ومتطلبات العملاء.',categories:'استكشف الفئات',featured:'منتجات مميزة',showcase:'المعرض المرئي',documents:'وثائق الشركة',contactEyebrow:'تواصل معنا',contactTitle:'لنبنِ شيئاً',contactTitle2:'قوياً معاً.',contactDesc:'أخبرنا عن مشروعك وتواصل مباشرة مع فريقنا.'},
 pages:{about:{title:'عن المطيري للفيبر جلاس',sub:'شريكك العملي في حلول الفيبر جلاس بجدة.',eyebrow:'نهجنا',heading:'الجودة ليست مجرد ميزة.',heading2:'بل هي معيارنا.',p1:'يركز المطيري للفيبر جلاس على أعمال الفيبر جلاس المتينة والتصنيع حسب الطلب والحلول المبنية على احتياجات العملاء الفعلية.',p2:'من المنتجات اليومية إلى المتطلبات المتخصصة، هدفنا واضح: تنفيذ موثوق وتصميم عملي وخدمة يمكنك الوثوق بها.'},products:{title:'منتجاتنا',sub:'50 منتجاً ضمن ثماني فئات عملية من الفيبر جلاس.'},showcase:{title:'المعرض المرئي',sub:'استكشف أعمالنا من خلال فيديوهات المعرض.'},documents:{title:'وثائق الشركة',sub:'تصفح جميع وثائق الشركة المتاحة.'},faq:{title:'الأسئلة الشائعة',sub:'إجابات سريعة حول المنتجات والخدمات وطرق التواصل.'},contact:{title:'تواصل معنا',sub:'أخبرنا بما تحتاج إليه وتواصل معنا مباشرة.'}},
 categories:['الخزانات والحاويات','المظلات والظلال','الأبواب والنوافذ','الفيبر جلاس الصناعي','البحري والخارجي','التصنيع حسب الطلب','الفيبر جلاس الديكوري','الإصلاح والصيانة'],
 categoryDesc:['خزانات وحلول تخزين متينة.','مظلات وحلول حماية مقاومة للعوامل الجوية.','أبواب ونوافذ قوية وقليلة الصيانة.','حلول عملية للبيئات الصناعية.','منتجات فيبر جلاس للاستخدام البحري والخارجي.','تصنيع فيبر جلاس حسب المقاسات والطلب.','قطع ديكورية بتشطيبات متينة.','خدمات الإصلاح والترميم والصيانة.'],
 productModel:'موديل',productSearch:'ابحث عن المنتجات…',all:'الكل',view:'عرض',documents:'وثيقة الشركة',
 faqs:[['ما المنتجات التي يوفرها المطيري للفيبر جلاس؟','نوفر منتجات الفيبر جلاس وحلولاً مخصصة للاستخدامات السكنية والتجارية والصناعية والبحرية والخارجية.'],['أين يقع المطيري للفيبر جلاس؟','يقع المطيري للفيبر جلاس في شارع الثلاثين بالقرب من شارع الستين، جدة 23448، المملكة العربية السعودية.'],['هل يمكنكم تصنيع منتجات فيبر جلاس حسب الطلب؟','نعم. أرسل المقاسات والكمية والصور المرجعية والمتطلبات عبر واتساب للحصول على عرض سعر مخصص.'],['كيف يمكنني طلب عرض سعر؟','استخدم نموذج تواصل معنا أو زر واتساب وأخبرنا بما تحتاج إليه.'],['هل تقدمون خدمات الإصلاح والصيانة؟','نعم، يمكن مناقشة الإصلاح والصيانة حسب حالة المنتج أو المشروع.'],['كيف يمكنني التواصل مع الشركة؟','اتصل على +966 50 251 1885 أو تواصل معنا عبر واتساب.']],
 footer:{desc:'حلول فيبر جلاس احترافية في جدة، المملكة العربية السعودية.',explore:'استكشف',contact:'تواصل',maps:'خرائط جوجل'},form:{name:'الاسم',phone:'رقم الهاتف',message:'الرسالة'}
 }
}

const showcase=[1,2,3,4,5,6,7,8,9,10].map(i=>`${A}v${i}.mp4`)
const docs=Array.from({length:16},(_,i)=>({id:i+1,image:`${A}d${i+1}.jpeg`}))

function App(){
 const[page,setPage]=useState('home'),[menu,setMenu]=useState(false),[lang,setLang]=useState('en'),[cat,setCat]=useState('All'),[q,setQ]=useState(''),[light,setLight]=useState(null),[faq,setFaq]=useState(0)
 const L=I18N[lang]
 const catNames=I18N.en.categories
 const categories=catNames.map((name,i)=>({name,image:`${A}c${i+1}.jpeg`,desc:L.categoryDesc[i]}))
 const products=Array.from({length:50},(_,i)=>({id:i+1,name:`${L.categories[i%8]} — ${L.productModel} ${i+1}`,image:`${A}pr${i+1}.jpeg`,category:L.categories[i%8],enCategory:catNames[i%8]}))
 const filtered=useMemo(()=>products.filter(p=>(cat==='All'||p.enCategory===cat)&&p.name.toLowerCase().includes(q.toLowerCase())),[cat,q,lang])
 const go=p=>{setPage(p);setMenu(false);scrollTo(0,0)}
 const toggleLanguage=()=>setLang(x=>x==='en'?'ar':'en')
 return <div className={lang==='ar'?'rtl':''} lang={lang} dir={lang==='ar'?'rtl':'ltr'}>
  <header><div className="nav"><button className="logo" onClick={()=>go('home')}><b>AF</b><span>AL-MUTAIRI<small>FIBER GLASS</small></span></button><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?'open':''}>{Object.entries(L.nav).map(([key,label])=><button className={page===key?'on':''} onClick={()=>go(key)} key={key}>{label}</button>)}</nav><div className="actions"><button onClick={toggleLanguage}>{lang==='en'?'العربية':'EN'}</button><a href={WA} target="_blank">WhatsApp</a></div></div></header>
  {page==='home'&&<Home L={L} go={go} setLight={setLight} categories={categories} products={products}/>} 
  {page==='about'&&<About L={L} go={go}/>} 
  {page==='products'&&<Products L={L} filtered={filtered} cat={cat} setCat={setCat} q={q} setQ={setQ} setLight={setLight}/>} 
  {page==='showcase'&&<Showcase L={L}/>} 
  {page==='documents'&&<Documents L={L} setLight={setLight}/>} 
  {page==='faq'&&<FAQ L={L} faq={faq} setFaq={setFaq}/>} 
  {page==='contact'&&<Contact L={L}/>} 
  <Footer L={L} go={go}/>
  {light&&<div className="lightbox" onClick={()=>setLight(null)}><img src={light}/><button>×</button></div>}
 </div>
}

function Hero({title,sub}){return <section className="pageHero"><span>AL-MUTAIRI FIBER GLASS • JEDDAH</span><h1>{title}</h1><p>{sub}</p></section>}
function Home({L,go,setLight,categories,products}){return <main><section className="hero" style={{backgroundImage:`url(${A}hero.jpeg)`}}><div className="shade"/><div className="heroText"><span>{L.home.eyebrow}</span><h1>{L.home.title}<br/><i>{L.home.title2}</i></h1><p>{L.home.desc}</p><div><button className="gold" onClick={()=>go('products')}>{L.buttons.explore}</button><a className="outline" href={WA} target="_blank">{L.buttons.whatsapp}</a></div><div className="stats"><b>50+<small>{L.home.stats[0]}</small></b><b>8<small>{L.home.stats[1]}</small></b><b>Jeddah<small>{L.home.stats[2]}</small></b></div></div></section>
 <section className="section intro"><div><span>{L.home.company}</span><h2>{L.home.companyTitle}<br/><i>{L.home.companyTitle2}</i></h2></div><div><p>{L.home.companyDesc}</p><button className="link" onClick={()=>go('about')}>{L.buttons.discover}</button></div></section>
 <section className="section"><Head title={L.home.categories} action={()=>go('products')} L={L}/><div className="catGrid">{categories.map((c,i)=><button className="cat" onClick={()=>go('products')} key={c.name}><img src={c.image}/><div><b>{c.name}</b><span>{c.desc}</span></div></button>)}</div></section>
 <section className="section"><Head title={L.home.featured} action={()=>go('products')} L={L}/><div className="products">{products.slice(0,8).map(p=><Product p={p} setLight={setLight} L={L} key={p.id}/>)}</div></section>
 <section className="dark section"><Head title={L.home.showcase} action={()=>go('showcase')} L={L}/><div className="videos">{showcase.map(v=><video key={v} src={v} autoPlay muted loop playsInline controls/>)}</div></section>
 <section className="section"><Head title={L.home.documents} action={()=>go('documents')} L={L}/><div className="docs">{docs.slice(0,5).map(d=><button onClick={()=>setLight(d.image)} key={d.image}><img src={d.image}/><span>{L.documents} {d.id}</span></button>)}</div></section>
 <section className="contactSplit"><img src={A+'g.jpeg'}/><div><span>{L.home.contactEyebrow}</span><h2>{L.home.contactTitle}<br/><i>{L.home.contactTitle2}</i></h2><p>{L.home.contactDesc}</p><a className="gold" href={WA} target="_blank">{L.buttons.message}</a><a className="darkBtn" href={MAP} target="_blank">{L.buttons.maps}</a></div></section></main>}
function Head({title,action,L}){return <div className="head"><h2>{title}</h2><button onClick={action}>{L.buttons.view}</button></div>}
function Product({p,setLight,L}){return <button className="product" onClick={()=>setLight(p.image)}><div><img src={p.image}/><em>{L.view}</em></div><small>{p.category}</small><b>{p.name}</b></button>}
function About({L,go}){const p=L.pages.about;return <main><Hero title={p.title} sub={p.sub}/><section className="section about"><div><span>{p.eyebrow}</span><h2>{p.heading}<br/><i>{p.heading2}</i></h2></div><div><p>{p.p1}</p><p>{p.p2}</p><button className="gold" onClick={()=>go('contact')}>{L.buttons.conversation}</button></div></section></main>}
function Products({L,filtered,cat,setCat,q,setQ,setLight}){return <main><Hero title={L.pages.products.title} sub={L.pages.products.sub}/><section className="section"><div className="filter"><div><button className={cat==='All'?'selected':''} onClick={()=>setCat('All')}>{L.all}</button>{I18N.en.categories.map((c,i)=><button className={cat===c?'selected':''} onClick={()=>setCat(c)} key={c}>{L.categories[i]}</button>)}</div><input placeholder={L.productSearch} value={q} onChange={e=>setQ(e.target.value)}/></div><div className="products">{filtered.map(p=><Product p={p} setLight={setLight} L={L} key={p.id}/>)}</div></section></main>}
function Showcase({L}){return <main><Hero title={L.pages.showcase.title} sub={L.pages.showcase.sub}/><section className="section dark"><div className="videos">{showcase.map(v=><video key={v} src={v} autoPlay muted loop playsInline controls preload="none"/>)}</div></section></main>}
function Documents({L,setLight}){return <main><Hero title={L.pages.documents.title} sub={L.pages.documents.sub}/><section className="section"><div className="docs all">{docs.map(d=><button onClick={()=>setLight(d.image)} key={d.image}><img src={d.image}/><span>{L.documents} {d.id}</span></button>)}</div></section></main>}
function FAQ({L,faq,setFaq}){return <main><Hero title={L.pages.faq.title} sub={L.pages.faq.sub}/><section className="section faqWrap"><img src={A+'f.jpeg'}/><div>{L.faqs.map((x,i)=><button className="faq" onClick={()=>setFaq(faq===i?-1:i)} key={x[0]}><header><span>0{i+1}</span><b>{x[0]}</b><strong>{faq===i?'−':'+'}</strong></header>{faq===i&&<p>{x[1]}</p>}</button>)}</div></section></main>}
function Contact({L}){const[f,setF]=useState({name:'',phone:'',message:''});const send=e=>{e.preventDefault();window.open(`${WA}?text=${encodeURIComponent(`${L.nav.contact} - Al-Mutairi Fiber Glass. ${L.form.name}: ${f.name}. ${L.form.phone}: ${f.phone}. ${L.form.message}: ${f.message}`)}`,'_blank')};return <main><Hero title={L.pages.contact.title} sub={L.pages.contact.sub}/><section className="section contact"><div><img src={A+'g.jpeg'}/><h3>Al-Mutairi Fiber Glass</h3><p>30th Street, near 60th<br/>Jeddah 23448, Saudi Arabia</p><a href={MAP} target="_blank">{L.buttons.openLocation}</a><a href={`tel:${PHONE.replaceAll(' ','')}`}>{PHONE}</a></div><form onSubmit={send}><label>{L.form.name}<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>{L.form.phone}<input required value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>{L.form.message}<textarea required rows="7" value={f.message} onChange={e=>setF({...f,message:e.target.value})}/></label><button className="gold">{L.buttons.send}</button></form></section></main>}
function Footer({L,go}){return <footer><div><b>AF</b><h3>Al-Mutairi Fiber Glass</h3><p>{L.footer.desc}</p></div><div><h4>{L.footer.explore}</h4><button onClick={()=>go('about')}>{L.nav.about}</button><button onClick={()=>go('products')}>{L.nav.products}</button><button onClick={()=>go('showcase')}>{L.nav.showcase}</button></div><div><h4>{L.footer.contact}</h4><a href={WA} target="_blank">WhatsApp</a><a href={`tel:${PHONE.replaceAll(' ','')}`}>{PHONE}</a><a href={MAP} target="_blank">{L.footer.maps}</a></div><small>© 2026 Al-Mutairi Fiber Glass • المطيري للفيبر جلاس</small></footer>}

createRoot(document.getElementById('root')).render(<App/>)
